# To evaluate the availability of South Indian food in the number of hotels or restaurants in certain of India's major cities.

In [1]:
import requests
from bs4 import BeautifulSoup
import re
import numpy as np
import pandas as pd

In [2]:
url="https://www.swiggy.com/city/bangalore/south-indian-collection?page=4"

In [3]:
page=requests.get(url)

In [4]:
page

In [5]:
## Bangalore-df

Restaurant,Cuisine,Coupon,Rating,Delivered_in,Budget,People

In [6]:
restaurant=[]
cuisine=[]
coupon=[]
rating=[]
delivered_in=[]
budget=[]
people=[]
for i in range(1,9):
    url="https://www.swiggy.com/city/bangalore/south-indian-collection?page="+str(i)
    print(url)
    page=requests.get(url)
    soup=BeautifulSoup(page.content)
    
    a= soup.find_all('div', class_="nA6kb")
    for i in a:
        restaurant.append(i.text)
        
    b= soup.find_all('div', class_="_1gURR")
    for i in b:
        cuisine.append(i.text)  
        
    d= soup.find_all('span', class_="sNAfh")
    for i in d:
        coupon.append(i.text)
        
    
    e=soup.find_all('div', class_="_3Mn31")
    for i in e:
        rating.append(i.text.split("•")[0])
        delivered_in.append(i.text.split("•")[1].split(" ")[0])
        budget.append(i.text.split("₹")[1].split(" ")[0])
        
        
print(len(restaurant))
print(len(cuisine))
print(len(coupon))
print(len(rating))
print(len(delivered_in))
print(len(budget))

https://www.swiggy.com/city/bangalore/south-indian-collection?page=1
https://www.swiggy.com/city/bangalore/south-indian-collection?page=2
https://www.swiggy.com/city/bangalore/south-indian-collection?page=3
https://www.swiggy.com/city/bangalore/south-indian-collection?page=4
https://www.swiggy.com/city/bangalore/south-indian-collection?page=5
https://www.swiggy.com/city/bangalore/south-indian-collection?page=6
https://www.swiggy.com/city/bangalore/south-indian-collection?page=7
https://www.swiggy.com/city/bangalore/south-indian-collection?page=8
128
128
130
128
128
128

In [7]:
df=pd.DataFrame({'Restaurant':restaurant, 'Cuisine':cuisine, 'Coupon':coupon[0:128], 'Rating':rating,"Delivery_time":delivered_in,"Price per two":budget})

In [8]:
city=["Bangalore"]
r=128
l= []
for i in city:
    for ele in range(r):
        l.append(i)
print(l)

['Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore', 'Bangalore']

In [9]:
df["Location"]=l

In [12]:
df

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,Meghana Foods,"Biryani, Andhra, South Indian, North Indian, C...",50% off | Use WELCOME50,4.3,37,500,Bangalore
1,Ayodhya Upachar,"Chinese, Desserts, North Indian, South Indian,...",50% off | Use WELCOME50,4.4,36,200,Bangalore
2,Puliyogare Point,South Indian,50% off | Use WELCOME50,4.5,23,150,Bangalore
3,N R Donne Biriyani,"Biryani, South Indian",50% off | Use GUILTFREEJAN,4.2,31,250,Bangalore
4,Hotel Kadamba Veg,"South Indian, North Indian, Chinese, Sweets",50% off | Use WELCOME50,4.3,43,350,Bangalore
...,...,...,...,...,...,...,...
123,Lakshmi food point,"South Indian, Indian",50% off | Use WELCOME50,--,42,200,Bangalore
124,Mayura 1989,"Chinese, South Indian, North Indian, Desserts,...",50% off | Use GUILTFREEJAN,4.2,31,900,Bangalore
125,Bob's Bar,"South Indian, North Indian, Desserts",10% off | Use TRYNEW,4.3,50,300,Bangalore
126,SLV Swadishta (South Indian),South Indian,50% off | Use WELCOME50,4.5,30,300,Bangalore
127,Udupi Sri Krishna Bhavan,South Indian,50% off | Use WELCOME50,4.4,27,200,Bangalore

In [13]:
df.to_csv("df.csv")

In [252]:
update_df=df.drop(index=[83,84,85,87,89,90,91,93,96,98,99,100,102,105,104,106,108,110,112,115,121,123])

In [253]:
update_df

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,Meghana Foods,"Biryani, Andhra, South Indian, North Indian, C...",50% off | Use WELCOME50,4.3,37,500,Bangalore
1,Ayodhya Upachar,"Chinese, Desserts, North Indian, South Indian,...",50% off | Use WELCOME50,4.4,36,200,Bangalore
2,Puliyogare Point,South Indian,50% off | Use WELCOME50,4.5,23,150,Bangalore
3,N R Donne Biriyani,"Biryani, South Indian",50% off | Use GUILTFREEJAN,4.2,31,250,Bangalore
4,Hotel Kadamba Veg,"South Indian, North Indian, Chinese, Sweets",50% off | Use WELCOME50,4.3,43,350,Bangalore
...,...,...,...,...,...,...,...
122,Chai Point,"Bakery, Beverages, Maharashtrian, Snacks, Stre...",50% off | Use WELCOME50,4.3,34,150,Bangalore
124,Mayura 1989,"Chinese, South Indian, North Indian, Desserts,...",50% off | Use GUILTFREEJAN,4.2,31,900,Bangalore
125,Bob's Bar,"South Indian, North Indian, Desserts",10% off | Use TRYNEW,4.3,50,300,Bangalore
126,SLV Swadishta (South Indian),South Indian,50% off | Use WELCOME50,4.5,30,300,Bangalore
127,Udupi Sri Krishna Bhavan,South Indian,50% off | Use WELCOME50,4.4,27,200,Bangalore

In [254]:
update_df.to_csv("update_df.csv")

In [17]:
0#hyd=df2

In [18]:
url1="https://www.swiggy.com/city/hyderabad/south-indian-collection"

In [19]:
page=requests.get(url1)

In [20]:
page

In [109]:
restaurant=[]
cuisine=[]
coupon=[]
rating=[]
delivered_in=[]
budget=[]
people=[]
for i in range(1,9):
    url="https://www.swiggy.com/city/hyderabad/south-indian-collection?page="+str(i)
    print(url)
    page=requests.get(url)
    soup=BeautifulSoup(page.content)
    a= soup.find_all('div', class_="nA6kb")
    for i in a:
        restaurant.append(i.text)
    b= soup.find_all('div', class_="_1gURR")
    for i in b:
        cuisine.append(i.text)    
    d= soup.find_all('span', class_="sNAfh")
    for i in d:
        coupon.append(i.text)
    
    e=soup.find_all('div', class_="_3Mn31")
    for i in e:
        rating.append(i.text.split("•")[0])
        delivered_in.append(i.text.split("•")[1].split(" ")[0])
        budget.append(i.text.split("₹")[1].split(" ")[0])
        people.append(i.text.split("₹")[1].split(" ")[2])
        
print(len(restaurant))
print(len(cuisine))
print(len(coupon))
print(len(rating))
print(len(delivered_in))
print(len(budget))

https://www.swiggy.com/city/hyderabad/south-indian-collection?page=1
https://www.swiggy.com/city/hyderabad/south-indian-collection?page=2
https://www.swiggy.com/city/hyderabad/south-indian-collection?page=3
https://www.swiggy.com/city/hyderabad/south-indian-collection?page=4
https://www.swiggy.com/city/hyderabad/south-indian-collection?page=5
https://www.swiggy.com/city/hyderabad/south-indian-collection?page=6
https://www.swiggy.com/city/hyderabad/south-indian-collection?page=7
https://www.swiggy.com/city/hyderabad/south-indian-collection?page=8
128
128
131
128
128
128

In [110]:
df2=pd.DataFrame({'Restaurant':restaurant, 'Cuisine':cuisine, 'Coupon':coupon[0:128], 'Rating':rating,"Delivery_time":delivered_in,"Price per two":budget})

In [111]:
city1=["Hyderabad"]
K1=128
res1 = []
for i in city1:
    for ele in range(K1):
        res1.append(i)
print(res1)

['Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad', 'Hyderabad']

In [112]:
df2['Location']=res1

In [113]:
df2

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,Vasista's Sri Lakshmi,"Biryani, Tandoor, Chinese, North Indian, South...",50% off | Use WELCOME50,4.0,26,350,Hyderabad
1,Lucky Multicuisine Restaurant,"Biryani, North Indian, Tandoor, South Indian",50% off | Use WELCOME50,3.5,27,400,Hyderabad
2,Vivaha Bhojanambu,"South Indian, Biryani, Andhra, Chinese, Tandoor",50% off | Use WELCOME50,3.8,29,500,Hyderabad
3,Meghduth Biryanis,"Biryani, Chinese, Andhra, South Indian",40% off on all orders,3.5,31,250,Hyderabad
4,Subbayya Gari Hotel,"South Indian, Andhra, Sweets",FREE DELIVERY,3.7,39,400,Hyderabad
...,...,...,...,...,...,...,...
123,Teluguness,South Indian,50% off | Use WELCOME50,3.8,45,700,Hyderabad
124,Shree Meghana Foods Take Away,"Chinese, Indian, South Indian, Home Food",50% off | Use WELCOME50,3.3,36,250,Hyderabad
125,South by Cravery,South Indian,50% off | Use WELCOME50,--,35,600,Hyderabad
126,KUKI (KURNOOL KITCHEN),"South Indian, Andhra",50% off | Use WELCOME50,4.0,43,200,Hyderabad
127,B Curries (by Biryanis & More),"Indian, South Indian, Thalis",50% off | Use WELCOME50,3.0,43,200,Hyderabad

In [114]:
df2.to_csv("df2.csv")

In [118]:
update_df2=df2.drop(index=[33,34,36,39,41,42,43,101,104,105,108,109,113,115,116,117,119,121,122,124,125])

In [119]:
update_df2

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,Vasista's Sri Lakshmi,"Biryani, Tandoor, Chinese, North Indian, South...",50% off | Use WELCOME50,4.0,26,350,Hyderabad
1,Lucky Multicuisine Restaurant,"Biryani, North Indian, Tandoor, South Indian",50% off | Use WELCOME50,3.5,27,400,Hyderabad
2,Vivaha Bhojanambu,"South Indian, Biryani, Andhra, Chinese, Tandoor",50% off | Use WELCOME50,3.8,29,500,Hyderabad
3,Meghduth Biryanis,"Biryani, Chinese, Andhra, South Indian",40% off on all orders,3.5,31,250,Hyderabad
4,Subbayya Gari Hotel,"South Indian, Andhra, Sweets",FREE DELIVERY,3.7,39,400,Hyderabad
...,...,...,...,...,...,...,...
118,Syala 95A,"South Indian, Indian, Chinese",50% off | Use WELCOME50,4.1,34,400,Hyderabad
120,Mana Bhojanam,"South Indian, Indian",50% off | Use WELCOME50,3.6,41,500,Hyderabad
123,Teluguness,South Indian,50% off | Use WELCOME50,3.8,45,700,Hyderabad
126,KUKI (KURNOOL KITCHEN),"South Indian, Andhra",50% off | Use WELCOME50,4.0,43,200,Hyderabad
127,B Curries (by Biryanis & More),"Indian, South Indian, Thalis",50% off | Use WELCOME50,3.0,43,200,Hyderabad

In [121]:
update_df2.to_csv("update_df2.csv")

In [122]:
#chennai=df3

In [123]:
url2="https://www.swiggy.com/city/chennai/south-indian-collection"

In [124]:
page=requests.get(url2)

In [125]:
page

In [126]:
restaurant=[]
cuisine=[]
coupon=[]
rating=[]
delivered_in=[]
budget=[]
people=[]
for i in range(1,9):
    url="https://www.swiggy.com/city/chennai/south-indian-collection?page="+str(i)
    print(url)
    page=requests.get(url)
    soup=BeautifulSoup(page.content)
    a= soup.find_all('div', class_="nA6kb")
    for i in a:
        restaurant.append(i.text)
    b= soup.find_all('div', class_="_1gURR")
    for i in b:
        cuisine.append(i.text)    
    d= soup.find_all('span', class_="sNAfh")
    for i in d:
        coupon.append(i.text)
    
    e=soup.find_all('div', class_="_3Mn31")
    for i in e:
        rating.append(i.text.split("•")[0])
        delivered_in.append(i.text.split("•")[1].split(" ")[0])
        budget.append(i.text.split("₹")[1].split(" ")[0])
        people.append(i.text.split("₹")[1].split(" ")[2])
        
print(len(restaurant))
print(len(cuisine))
print(len(coupon))
print(len(rating))
print(len(delivered_in))
print(len(budget))
print(len(people))

https://www.swiggy.com/city/chennai/south-indian-collection?page=1
https://www.swiggy.com/city/chennai/south-indian-collection?page=2
https://www.swiggy.com/city/chennai/south-indian-collection?page=3
https://www.swiggy.com/city/chennai/south-indian-collection?page=4
https://www.swiggy.com/city/chennai/south-indian-collection?page=5
https://www.swiggy.com/city/chennai/south-indian-collection?page=6
https://www.swiggy.com/city/chennai/south-indian-collection?page=7
https://www.swiggy.com/city/chennai/south-indian-collection?page=8
20
20
20
20
20
20
20

In [127]:
df3=pd.DataFrame({'Restaurant':restaurant, 'Cuisine':cuisine, 'Coupon':coupon, 'Rating':rating,"Delivery_time":delivered_in,"Price per two":budget})

In [131]:
city2=["Chennai"]
r2=20
l2 = []
for i in city2:
    for ele in range(r2):
        l2.append(i)
print(l2)

['Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai']

In [132]:
df3["Location"]=l2

In [133]:
df3

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,SRM Chettinadu Unavagam,"South Indian, Biryani, Fast Food",50% off | Use WELCOME50,--,34,500,Chennai
1,Sangeetha Veg Restaurant,"Chinese, Indian, North Indian, South Indian",50% off | Use WELCOME50,4.3,38,200,Chennai
2,Shaadi Biriyani,"Biryani, Chinese, South Indian, Snacks",50% off | Use WELCOME50,3.8,47,300,Chennai
3,Appam Kadai,"South Indian, Combo, North Indian",50% off | Use WELCOME50,--,46,150,Chennai
4,Naattarasan,"Chettinad, North Indian, Chinese, South Indian",50% off | Use WELCOME50,4.0,45,400,Chennai
5,MS Biryani,"South Indian, Chinese",50% off | Use WELCOME50,4.2,32,250,Chennai
6,Ar rahaman biriyani,"Biryani, South Indian",50% off | Use WELCOME50,3.4,38,100,Chennai
7,Arcot Biryani House,"South Indian, Biryani, North Indian",50% off | Use WELCOME50,3.8,28,250,Chennai
8,Loiee's veg restaurant,"North Indian, Chaat, Sweets, South Indian, Chi...",40% off | Use GUILTFREEJAN,4.0,42,250,Chennai
9,GRK HOTEL,"South Indian, Chinese",FREE DELIVERY,4.0,39,250,Chennai
10,S V Homemade Gourmet Food Corner,"Street Food, South Indian, Chinese, Indian",50% off | Use WELCOME50,--,43,200,Chennai
11,Shero Home Food - Chettinad,"South Indian, Healthy Food, Home Food, Desserts",50% off | Use WELCOME50,3.9,62,350,Chennai
12,NITHYA HOME FOODS,"South Indian, Indian",FREE DELIVERY,3.8,55,1000,Chennai
13,Divya Tiffin Center,"South Indian, Desserts",50% off | Use WELCOME50,--,46,200,Chennai
14,ARASAMPATTI CHETTINAD FAMILY RESTAURANT,"Chettinad, Biryani, North Indian, South Indian...",50% off | Use WELCOME50,3.0,43,250,Chennai
15,Shree Iyyah's Annabrahmam,"South Indian, Chinese",50% off | Use WELCOME50,3.7,43,300,Chennai
16,Hotel Royal Food Corner,"Chinese, South Indian, Biryani",50% off | Use WELCOME50,--,49,200,Chennai
17,Siddhu Kitchen,South Indian,50% off | Use WELCOME50,--,42,300,Chennai
18,Rice N Gravy,"Indian, South Indian, Chinese",50% off | Use WELCOME50,1.8,47,200,Chennai
19,PARROTA PARADISE,"North Indian, South Indian, Chinese, Combo",50% off | Use WELCOME50,--,40,200,Chennai

In [134]:
df3.to_csv("df3.csv")

In [138]:
update_df3=df3.drop(index=[0,2,3,6,10,12,13,14,15,16,17,18,19])

In [139]:
update_df3

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
1,Sangeetha Veg Restaurant,"Chinese, Indian, North Indian, South Indian",50% off | Use WELCOME50,4.3,38,200,Chennai
4,Naattarasan,"Chettinad, North Indian, Chinese, South Indian",50% off | Use WELCOME50,4.0,45,400,Chennai
5,MS Biryani,"South Indian, Chinese",50% off | Use WELCOME50,4.2,32,250,Chennai
7,Arcot Biryani House,"South Indian, Biryani, North Indian",50% off | Use WELCOME50,3.8,28,250,Chennai
8,Loiee's veg restaurant,"North Indian, Chaat, Sweets, South Indian, Chi...",40% off | Use GUILTFREEJAN,4.0,42,250,Chennai
9,GRK HOTEL,"South Indian, Chinese",FREE DELIVERY,4.0,39,250,Chennai
11,Shero Home Food - Chettinad,"South Indian, Healthy Food, Home Food, Desserts",50% off | Use WELCOME50,3.9,62,350,Chennai

In [140]:
update_df3.to_csv("update_df3.csv")

In [141]:
#noida-1=df4

In [142]:
url3="https://www.swiggy.com/city/noida-1"

In [143]:
page=requests.get(url3)

In [144]:
page

In [145]:
restaurant=[]
cuisine=[]
coupon=[]
rating=[]
delivered_in=[]
budget=[]
people=[]
for i in range(1,9):
    url="https://www.swiggy.com/city/noida-1?page="+str(i)
    print(url)
    page=requests.get(url)
    soup=BeautifulSoup(page.content)
    a= soup.find_all('div', class_="nA6kb")
    for i in a:
        restaurant.append(i.text)
    b= soup.find_all('div', class_="_1gURR")
    for i in b:
        cuisine.append(i.text)    
    d= soup.find_all('span', class_="sNAfh")
    for i in d:
        coupon.append(i.text)
    
    e=soup.find_all('div', class_="_3Mn31")
    for i in e:
        rating.append(i.text.split("•")[0])
        delivered_in.append(i.text.split("•")[1].split(" ")[0])
        budget.append(i.text.split("₹")[1].split(" ")[0])
        people.append(i.text.split("₹")[1].split(" ")[2])
        
print(len(restaurant))
print(len(cuisine))
print(len(coupon))
print(len(rating))
print(len(delivered_in))
print(len(budget))
print(len(people))

https://www.swiggy.com/city/noida-1?page=1
https://www.swiggy.com/city/noida-1?page=2
https://www.swiggy.com/city/noida-1?page=3
https://www.swiggy.com/city/noida-1?page=4
https://www.swiggy.com/city/noida-1?page=5
https://www.swiggy.com/city/noida-1?page=6
https://www.swiggy.com/city/noida-1?page=7
https://www.swiggy.com/city/noida-1?page=8
128
128
129
128
128
128
128

In [146]:
df4=pd.DataFrame({'Restaurant':restaurant, 'Cuisine':cuisine, 'Coupon':coupon[0:128], 'Rating':rating,"Delivery_time":delivered_in,"Price per two":budget})

In [218]:
city3=["Noida"]
r3=128
l3 = []
for i in city3:
    for ele in range(r3):
        l3.append(i)
print(l3)

['Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida', 'Noida']

In [219]:
df4["Location"]=l3

In [220]:
df4

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,KFC,"Burgers, Biryani, American, Snacks, Fast Food",20% off | Use SWIGGYIT,3.9,30,450,Noida
1,Khan's Kathi Roll,"Chinese, Beverages, Mughlai",50% off | Use WELCOME50,3.7,21,150,Noida
2,Roshni Egg Roll Corner,"Kebabs, North Indian, Street Food",50% off | Use WELCOME50,4.1,21,300,Noida
3,The Royal Kitchen,"North Indian, Chinese, Mughlai",50% off | Use TRYNEW,4.0,31,350,Noida
4,Nirula's,"Desserts, Ice Cream, Beverages, Ice Cream Cake...",50% off | Use WELCOME50,4.7,23,500,Noida
...,...,...,...,...,...,...,...
123,Kathi Junction,Indian,50% off | Use WELCOME50,3.6,31,300,Noida
124,Pizza Paradise,Pizzas,50% off | Use WELCOME50,--,31,250,Noida
125,Saladify,"Healthy Food, Salads, Beverages",50% off | Use WELCOME50,3.5,31,400,Noida
126,The Spices And More,North Indian,50% off | Use WELCOME50,3.5,31,350,Noida
127,Anands,"Indian, Chinese",50% off | Use WELCOME50,--,32,400,Noida

In [221]:
df4.to_csv("df4.csv")

In [222]:
update_df4=df4.drop(index=[1,5,7,8,13,17,22,23,27,28,30,31,32,33,36,37,38,39,40,42,43,44,45,46,48,49,50,51,52,56,57,58,59,60,61,62,65,66,68,69,70,72,73,75,76,81,82,86,87,88,89,90,91,92,93,94,95,96,97,99,100,101,105,106,108,109,110,111,112,113,114,115,116,117,118,124,125,126,127,14,16,20,26,34,41,47,53,54,77,79,80,102,103,104,107,120,121,122])

In [223]:
update_df4

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,KFC,"Burgers, Biryani, American, Snacks, Fast Food",20% off | Use SWIGGYIT,3.9,30,450,Noida
2,Roshni Egg Roll Corner,"Kebabs, North Indian, Street Food",50% off | Use WELCOME50,4.1,21,300,Noida
3,The Royal Kitchen,"North Indian, Chinese, Mughlai",50% off | Use TRYNEW,4.0,31,350,Noida
4,Nirula's,"Desserts, Ice Cream, Beverages, Ice Cream Cake...",50% off | Use WELCOME50,4.7,23,500,Noida
6,Chaayos Chai+Snacks=Relax,"Bakery, Beverages, Chaat, Desserts, Fast Food,...",50% off | Use WELCOME50,4.3,28,250,Noida
9,Curry Mahal,"Indian, North Indian, Biryani, Thalis",50% off | Use WELCOME50,3.8,32,350,Noida
10,Aggarwal Sweets & Snacks,"Sweets, Snacks",20% off | Use TRYNEW,3.1,23,99,Noida
11,Burger King,"Burgers, American",60% off | Use STEALDEAL,4.1,23,350,Noida
12,House of Chow,"Pan-Asian, Chinese, Thai, Oriental",50% off | Use WELCOME50,3.9,33,300,Noida
15,The Burger Club,"American, Beverages",50% off | Use GUILTFREEJAN,4.1,38,300,Noida
18,Biryani Blues,"Biryani, Hyderabadi, Lucknowi, Kebabs",50% off | Use GUILTFREEJAN,4.4,32,400,Noida
19,Giani Ice Cream,"Mughlai, North Indian, Chinese",50% off | Use WELCOME50,4.3,24,400,Noida
21,Biryani By Kilo,"Biryani, Hyderabadi, North Indian, Kebabs, Mug...",40% off | Use TRYNEW,4.1,47,700,Noida
24,Bakingo,Bakery,50% off | Use WELCOME50,4.2,32,300,Noida
25,Shama Chicken Corner,North Indian,50% off | Use WELCOME50,3.8,25,400,Noida
29,NIC Ice Creams,"Ice Cream, Desserts",50% off | Use WELCOME50,4.5,25,120,Noida
35,BOX8 - Desi Meals,"North Indian, Biryani, Thalis, Home Food",50% off | Use WELCOME50,4.1,26,250,Noida
55,Cheesecake & Co.,"Bakery, Desserts",50% off | Use WELCOME50,4.5,28,400,Noida
63,Veg Always,"North Indian, Chinese, Biryani, Thalis, Desserts",50% off | Use WELCOME50,3.8,29,400,Noida
64,Rollsking,"North Indian, Fast Food, Beverages",40% off | Use GUILTFREEJAN,4.0,37,250,Noida
67,Paintra Samosa Lab,"Indian, Beverages",50% off | Use WELCOME50,3.8,37,299,Noida
71,Bakers Best,Bakery,50% off | Use WELCOME50,4.3,37,200,Noida
74,Yo! Chinese,Chinese,50% off | Use WELCOME50,2.3,38,200,Noida
78,Shri Kanha Restaurant,"North Indian, Street Food, Snacks",50% off | Use WELCOME50,3.8,38,250,Noida
83,Griller'Z,Indian,50% off | Use WELCOME50,3.5,30,250,Noida
84,Itminaan Matka Biryani - Slow Cooked,"Biryani, North Indian, Mughlai",50% off | Use WELCOME50,4.4,30,250,Noida
85,Mealful Rolls - India's Biggest Rolls,"Fast Food, Snacks, North Indian, Desserts",50% off | Use WELCOME50,3.7,30,250,Noida
98,The Waffle Co.,"Desserts, Waffle, Beverages",50% off | Use WELCOME50,4.3,31,200,Noida
119,Cake'O'Clocks,"Desserts, Bakery",50% off | Use WELCOME50,4.0,31,300,Noida
123,Kathi Junction,Indian,50% off | Use WELCOME50,3.6,31,300,Noida

In [155]:
update_df4.to_csv("update_df4.csv")

In [185]:
url4="https://www.swiggy.com/city/delhi/south-indian-collection"

In [186]:
page=requests.get(url4)

In [187]:
page

In [188]:
restaurant=[]
cuisine=[]
coupon=[]
rating=[]
delivered_in=[]
budget=[]
people=[]
for i in range(1,6):
    url="https://www.swiggy.com/city/delhi/south-indian-collection?page="+str(i)
    print(url)
    page=requests.get(url)
    soup=BeautifulSoup(page.content)
    a= soup.find_all('div', class_="nA6kb")
    for i in a:
        restaurant.append(i.text)
    b= soup.find_all('div', class_="_1gURR")
    for i in b:
        cuisine.append(i.text)    
    d= soup.find_all('span', class_="sNAfh")
    for i in d:
        coupon.append(i.text)
    
    e=soup.find_all('div', class_="_3Mn31")
    for i in e:
        rating.append(i.text.split("•")[0])
        delivered_in.append(i.text.split("•")[1].split(" ")[0])
        budget.append(i.text.split("₹")[1].split(" ")[0])
        people.append(i.text.split("₹")[1].split(" ")[2])
        
print(len(restaurant))
print(len(cuisine))
print(len(coupon))
print(len(rating))
print(len(delivered_in))
print(len(budget))
print(len(people))

https://www.swiggy.com/city/delhi/south-indian-collection?page=1
https://www.swiggy.com/city/delhi/south-indian-collection?page=2
https://www.swiggy.com/city/delhi/south-indian-collection?page=3
https://www.swiggy.com/city/delhi/south-indian-collection?page=4
https://www.swiggy.com/city/delhi/south-indian-collection?page=5
65
65
67
65
65
65
65

In [189]:
df5=pd.DataFrame({'Restaurant':restaurant, 'Cuisine':cuisine, 'Coupon':coupon[0:65], 'Rating':rating,"Delivery_time":delivered_in,"Price per two":budget})

In [191]:
city4=["Delhi"]
r4=65
l4 = []
for i in city4:
    for ele in range(r4):
        l4.append(i)
print(l4)

['Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi']

In [192]:
df5["Location"]=l4

In [193]:
df5

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,DURGA DOSA CORNER,"South Indian, Chinese",50% off | Use WELCOME50,4.2,25,200,Delhi
1,Durga Dosa,"South Indian, Chinese",50% off | Use WELCOME50,4.2,20,150,Delhi
2,New Durga Corner,"South Indian, Chinese",50% off | Use WELCOME50,4.1,23,150,Delhi
3,Haldiram's,"Sweets, South Indian, Chinese, Street Food, De...",FREE DELIVERY,4.2,26,450,Delhi
4,Gulab,"North Indian, South Indian, Chinese, Tandoor, ...",50% off | Use WELCOME50,4.2,27,200,Delhi
...,...,...,...,...,...,...,...
60,The Veggie Bites,"South Indian, Beverages",50% off | Use WELCOME50,3.9,38,300,Delhi
61,Jhakkas Pav Bhaji (Mumbai Wala),"South Indian, Fast Food",50% off | Use WELCOME50,3.7,37,250,Delhi
62,Shree Rathnam,"South Indian, North Indian, Chinese, Desserts",50% off | Use WELCOME50,4.3,41,600,Delhi
63,Punjabi Rasoi,"North Indian, Chinese, South Indian, Italian, ...",50% off | Use WELCOME50,4.2,40,400,Delhi
64,South Indian Junction,"South Indian, Chinese",50% off | Use WELCOME50,--,43,200,Delhi

In [194]:
df5.to_csv("df5.csv")

In [198]:
update_df5=df5.drop(index=[7,9,15,16,23,27,29,30,31,34,51,58,60,63,26,28,37,40,42,50,57,59,64])

In [199]:
update_df5

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,DURGA DOSA CORNER,"South Indian, Chinese",50% off | Use WELCOME50,4.2,25,200,Delhi
1,Durga Dosa,"South Indian, Chinese",50% off | Use WELCOME50,4.2,20,150,Delhi
2,New Durga Corner,"South Indian, Chinese",50% off | Use WELCOME50,4.1,23,150,Delhi
3,Haldiram's,"Sweets, South Indian, Chinese, Street Food, De...",FREE DELIVERY,4.2,26,450,Delhi
4,Gulab,"North Indian, South Indian, Chinese, Tandoor, ...",50% off | Use WELCOME50,4.2,27,200,Delhi
5,Sagar Ratna,"South Indian, North Indian, Chinese, Desserts",50% off | Use WELCOME50,4.1,24,450,Delhi
6,Hotel Saravana Bhavan,South Indian,50% off | Use WELCOME50,4.1,28,300,Delhi
8,Great Indian Khichdi by EatFit,"Home Food, Indian, North Indian, Healthy Food,...",40% off | Use GUILTFREEJAN,4.2,21,200,Delhi
10,Gulab Wala,"North Indian, Sweets, South Indian",50% off | Use WELCOME50,3.9,24,250,Delhi
11,Home Plate by EatFit,"North Indian, Home Food, Healthy Food, Indian,...",40% off | Use GUILTFREEJAN,4.1,23,160,Delhi
12,Biryani Badshah,"Biryani, Hyderabadi, Andhra, South Indian, Nor...",50% off | Use GUILTFREEJAN,4.1,23,400,Delhi
13,Bikanervala Raja Garden,"Street Food, Fast Food, Desserts, South Indian",50% off | Use WELCOME50,3.8,25,300,Delhi
14,Standard Snacks & Restaurant,"Snacks, North Indian, South Indian",50% off | Use WELCOME50,4.4,27,250,Delhi
17,South Indian Hut,South Indian,50% off | Use WELCOME50,3.9,24,400,Delhi
18,Murthal Express (By Imly),"North Indian, Tandoor, South Indian, Chinese, ...",50% off | Use WELCOME50,3.6,31,400,Delhi
19,Imly,"South Indian, Chinese, Street Food, Maharashtr...",50% off | Use WELCOME50,3.1,26,450,Delhi
20,Bowl Soul,"Indian, Asian, Continental, Pan-Asian, Chinese...",Get every item under 129,3.3,32,250,Delhi
21,MilletBowl By UrbanKisaan,"Healthy Food, South Indian, Biryani",FREE DELIVERY,4.3,26,250,Delhi
22,Hira Sweets,"North Indian, South Indian, Chinese, Continent...",50% off | Use WELCOME50,4.2,31,400,Delhi
24,Dakshin South Indian Hut,South Indian,50% off | Use WELCOME50,4.0,33,200,Delhi
25,South India Corner,South Indian,50% off | Use WELCOME50,4.0,25,200,Delhi
32,Mumbai Dosa Wala,South Indian,50% off | Use WELCOME50,3.9,37,150,Delhi
33,Nagpal Chholey Bhature (Ashok Vihar 1),"Street Food, North Indian, South Indian",50% off | Use WELCOME50,3.4,37,200,Delhi
35,Haldiram's,"Sweets, South Indian, Chinese, Street Food, De...",50% off | Use WELCOME50,4.2,26,450,Delhi
36,JAI SOUTH INDIAN DOSA CORNER,"Street Food, South Indian, Chinese",FREE DELIVERY,3.5,30,400,Delhi
38,MADRAS CAFE,South Indian,50% off | Use WELCOME50,3.5,36,200,Delhi
39,Standard Snacks & Restaurant,"Snacks, North Indian, South Indian",50% off | Use WELCOME50,4.4,27,250,Delhi
41,Biryani Badshah,"Biryani, Hyderabadi, Andhra, South Indian, Nor...",50% off | Use WELCOME50,4.1,23,400,Delhi
43,South Indian Fast Food,"South Indian, Chinese, North Indian",50% off | Use WELCOME50,4.0,37,200,Delhi
44,Vanakkam Madras Cafe,"South Indian, Chinese",50% off | Use WELCOME50,4.2,36,150,Delhi
45,Nivetha Dosa Corner,South Indian,50% off | Use WELCOME50,3.9,34,200,Delhi
46,Om Sweets & Snacks,"Sweets, North Indian, South Indian, Chinese, S...",50% off | Use WELCOME50,4.3,38,500,Delhi
47,Bowl Soul,"Indian, Asian, Continental, Pan-Asian, Chinese...",50% off | Use WELCOME50,3.3,32,250,Delhi
48,Nagpal Chholey Bhature (Ashok Vihar 1),"Street Food, North Indian, South Indian",Get every item under 129,3.4,37,200,Delhi
49,MADRAS CAFE,South Indian,FREE DELIVERY,3.5,36,200,Delhi
52,Nivetha Dosa Corner,South Indian,50% off | Use WELCOME50,3.9,34,200,Delhi
53,Hotel Annapurna,"Fast Food, Snacks, South Indian",50% off | Use WELCOME50,4.1,33,200,Delhi
54,Mr. Dosa (Pitampura),"South Indian, Chinese, Snacks, Beverages, Pan-...",50% off | Use WELCOME50,3.9,36,150,Delhi
55,Mumbai Dosa Wala,South Indian,50% off | Use WELCOME50,3.9,37,150,Delhi
56,Dosa Corner,"South Indian, Chinese",50% off | Use WELCOME50,4.3,32,200,Delhi
61,Jhakkas Pav Bhaji (Mumbai Wala),"South Indian, Fast Food",50% off | Use WELCOME50,3.7,37,250,Delhi
62,Shree Rathnam,"South Indian, North Indian, Chinese, Desserts",50% off | Use WELCOME50,4.3,41,600,Delhi

In [200]:
update_df5.to_csv("update_df5.csv")

In [201]:
url5="https://www.swiggy.com/city/lucknow/south-indian-collection"

In [202]:
page=requests.get(url5)

In [203]:
page

In [204]:
restaurant=[]
cuisine=[]
coupon=[]
rating=[]
delivered_in=[]
budget=[]
people=[]
for i in range(1,9):
    url="https://www.swiggy.com/city/lucknow/south-indian-collection?page="+str(i)
    print(url)
    page=requests.get(url)
    soup=BeautifulSoup(page.content)
    a= soup.find_all('div', class_="nA6kb")
    for i in a:
        restaurant.append(i.text)
    b= soup.find_all('div', class_="_1gURR")
    for i in b:
        cuisine.append(i.text)    
    d= soup.find_all('span', class_="sNAfh")
    for i in d:
        coupon.append(i.text)
    
    e=soup.find_all('div', class_="_3Mn31")
    for i in e:
        rating.append(i.text.split("•")[0])
        delivered_in.append(i.text.split("•")[1].split(" ")[0])
        budget.append(i.text.split("₹")[1].split(" ")[0])
        people.append(i.text.split("₹")[1].split(" ")[2])
        
print(len(restaurant))
print(len(cuisine))
print(len(coupon))
print(len(rating))
print(len(delivered_in))
print(len(budget))
print(len(people))

https://www.swiggy.com/city/lucknow/south-indian-collection?page=1
https://www.swiggy.com/city/lucknow/south-indian-collection?page=2
https://www.swiggy.com/city/lucknow/south-indian-collection?page=3
https://www.swiggy.com/city/lucknow/south-indian-collection?page=4
https://www.swiggy.com/city/lucknow/south-indian-collection?page=5
https://www.swiggy.com/city/lucknow/south-indian-collection?page=6
https://www.swiggy.com/city/lucknow/south-indian-collection?page=7
https://www.swiggy.com/city/lucknow/south-indian-collection?page=8
127
127
128
127
127
127
127

In [205]:
df6=pd.DataFrame({'Restaurant':restaurant, 'Cuisine':cuisine, 'Coupon':coupon[0:127], 'Rating':rating,"Delivery_time":delivered_in,"Price per two":budget})

In [206]:
city5=["Lucknow"]
r5=127
l5 = []
for i in city5:
    for ele in range(r5):
        l5.append(i)
print(l5)

['Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow', 'Lucknow']

In [207]:
df6["Location"]=l5

In [208]:
df6

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,"3C's ( Subhash ""The Mithai Shop"")","North Indian, Chinese, South Indian, Sweets",60% off | Use SPECIALS,4.1,37,250,Lucknow
1,Raj Luxmi Alambagh,"North Indian, Chinese, South Indian, Snacks",60% off | Use TRYNEW,4.0,31,300,Lucknow
2,Raj Luxmi Ashiyana,"North Indian, South Indian, Italian, Snacks",50% off | Use WELCOME50,4.1,38,250,Lucknow
3,Raj Luxmi Restaurant,"Indian, South Indian, Chinese, Sweets",60% off | Use TRYNEW,3.9,27,300,Lucknow
4,Next In,"North Indian, South Indian",50% off | Use WELCOME50,--,37,200,Lucknow
...,...,...,...,...,...,...,...
122,Maa Kripa,"North Indian, Chinese, Fast Food, Punjabi, Sou...",50% off | Use WELCOME50,--,70,200,Lucknow
123,Rang Chokha,"South Indian, Chinese",50% off | Use WELCOME50,3.8,51,300,Lucknow
124,MERIDIAN FOODS,"South Indian, Desserts",50% off | Use WELCOME50,--,56,400,Lucknow
125,Dosa House,South Indian,50% off | Use WELCOME50,3.8,45,200,Lucknow
126,Bikanervala,"Sweets, North Indian, South Indian, Continenta...",50% off | Use WELCOME50,4.1,49,300,Lucknow

In [209]:
df6.to_csv("df6.csv")

In [215]:
update_df6=df6.drop(index=[4,10,13,14,16,17,18,21,22,26,31,32,33,34,40,42,44,47,50,51,53,54,61,62,63,64,65,66,69,70,71,72,73,75,77,79,81,85,86,87,89,90,91,94,96,98,100,101,103,108,110,111,114,115,116,117,118,119,120,122,124,121,123])

In [216]:
update_df6

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,"3C's ( Subhash ""The Mithai Shop"")","North Indian, Chinese, South Indian, Sweets",60% off | Use SPECIALS,4.1,37,250,Lucknow
1,Raj Luxmi Alambagh,"North Indian, Chinese, South Indian, Snacks",60% off | Use TRYNEW,4.0,31,300,Lucknow
2,Raj Luxmi Ashiyana,"North Indian, South Indian, Italian, Snacks",50% off | Use WELCOME50,4.1,38,250,Lucknow
3,Raj Luxmi Restaurant,"Indian, South Indian, Chinese, Sweets",60% off | Use TRYNEW,3.9,27,300,Lucknow
5,Pandey's Shashwat Sweets,"Snacks, Desserts, South Indian, Chinese",50% off | Use WELCOME50,4.0,36,200,Lucknow
...,...,...,...,...,...,...,...
109,Madhurima Veg,"Indian, South Indian, Chinese, Snacks",50% off | Use WELCOME50,4.2,43,250,Lucknow
112,PATRAKAR BATI CHOKHA,"North Indian, South Indian, Snacks",50% off | Use WELCOME50,3.5,54,200,Lucknow
113,Sandy's Tiny & Tasty,"North Indian, Chinese, South Indian",50% off | Use WELCOME50,4.2,40,150,Lucknow
125,Dosa House,South Indian,50% off | Use WELCOME50,3.8,45,200,Lucknow
126,Bikanervala,"Sweets, North Indian, South Indian, Continenta...",50% off | Use WELCOME50,4.1,49,300,Lucknow

In [217]:
update_df6.to_csv("update_df6.csv")

In [225]:
v=v.reset_index(drop=True)

In [226]:
v

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,Meghana Foods,"Biryani, Andhra, South Indian, North Indian, C...",50% off | Use WELCOME50,4.3,37,500,Bangalore
1,Ayodhya Upachar,"Chinese, Desserts, North Indian, South Indian,...",50% off | Use WELCOME50,4.4,36,200,Bangalore
2,Puliyogare Point,South Indian,50% off | Use WELCOME50,4.5,23,150,Bangalore
3,N R Donne Biriyani,"Biryani, South Indian",50% off | Use GUILTFREEJAN,4.2,31,250,Bangalore
4,Hotel Kadamba Veg,"South Indian, North Indian, Chinese, Sweets",50% off | Use WELCOME50,4.3,43,350,Bangalore
...,...,...,...,...,...,...,...
365,Madhurima Veg,"Indian, South Indian, Chinese, Snacks",50% off | Use WELCOME50,4.2,43,250,Lucknow
366,PATRAKAR BATI CHOKHA,"North Indian, South Indian, Snacks",50% off | Use WELCOME50,3.5,54,200,Lucknow
367,Sandy's Tiny & Tasty,"North Indian, Chinese, South Indian",50% off | Use WELCOME50,4.2,40,150,Lucknow
368,Dosa House,South Indian,50% off | Use WELCOME50,3.8,45,200,Lucknow
369,Bikanervala,"Sweets, North Indian, South Indian, Continenta...",50% off | Use WELCOME50,4.1,49,300,Lucknow

In [227]:
url6="https://www.swiggy.com/city/kochi/south-indian-collection?page=1"

In [228]:
page=requests.get(url6)

In [229]:
page

In [230]:
restaurant=[]
cuisine=[]
coupon=[]
rating=[]
delivered_in=[]
budget=[]
people=[]
for i in range(1,9):
    url="https://www.swiggy.com/city/kochi/south-indian-collection?page="+str(i)
    print(url)
    page=requests.get(url)
    soup=BeautifulSoup(page.content)
    a= soup.find_all('div', class_="nA6kb")
    for i in a:
        restaurant.append(i.text)
    b= soup.find_all('div', class_="_1gURR")
    for i in b:
        cuisine.append(i.text)    
    d= soup.find_all('span', class_="sNAfh")
    for i in d:
        coupon.append(i.text)
    
    e=soup.find_all('div', class_="_3Mn31")
    for i in e:
        rating.append(i.text.split("•")[0])
        delivered_in.append(i.text.split("•")[1].split(" ")[0])
        budget.append(i.text.split("₹")[1].split(" ")[0])
        people.append(i.text.split("₹")[1].split(" ")[2])
        
print(len(restaurant))
print(len(cuisine))
print(len(coupon))
print(len(rating))
print(len(delivered_in))
print(len(budget))
print(len(people))

https://www.swiggy.com/city/kochi/south-indian-collection?page=1
https://www.swiggy.com/city/kochi/south-indian-collection?page=2
https://www.swiggy.com/city/kochi/south-indian-collection?page=3
https://www.swiggy.com/city/kochi/south-indian-collection?page=4
https://www.swiggy.com/city/kochi/south-indian-collection?page=5
https://www.swiggy.com/city/kochi/south-indian-collection?page=6
https://www.swiggy.com/city/kochi/south-indian-collection?page=7
https://www.swiggy.com/city/kochi/south-indian-collection?page=8
84
84
84
84
84
84
84

In [231]:
df7=pd.DataFrame({'Restaurant':restaurant, 'Cuisine':cuisine, 'Coupon':coupon, 'Rating':rating,"Delivery_time":delivered_in,"Price per two":budget})

In [232]:
df7

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two
0,Alakapuri,"South Indian, Kerala, North Indian",50% off | Use WELCOME50,4.4,32,300
1,Usmans,"South Indian, Arabian",50% off | Use WELCOME50,3.6,18,150
2,Pala Pepper,"Kerala, South Indian",50% off | Use WELCOME50,3.8,28,200
3,Hotel Shree Aryas,"South Indian, North Indian, Chinese, Beverages",50% off | Use WELCOME50,4.2,24,200
4,Hotel Sree Aryaas,"South Indian, North Indian, Chinese",50% off | Use WELCOME50,4.2,21,200
...,...,...,...,...,...,...
79,Dindigul Biriyani,"Biryani, South Indian",50% off | Use WELCOME50,3.6,36,250
80,pepper bite restaurant,"North Indian, Chinese, South Indian, Beverages",50% off | Use WELCOME50,3.9,42,280
81,Nila Restaurant,"South Indian, North Indian, Chinese",50% off | Use WELCOME50,4.1,48,200
82,Binnammas Food Gallery,"Kerala, South Indian, Chinese",50% off | Use WELCOME50,3.5,41,300
83,Pakka Sabji,"Indian, Chinese, South Indian",50% off | Use WELCOME50,4.1,42,500

In [233]:
city6=["Kochi"]
r6=84
l6 = []
for i in city6:
    for ele in range(r6):
        l6.append(i)
print(l6)

['Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi', 'Kochi']

In [234]:
df7["Location"]=l6

In [235]:
df7

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,Alakapuri,"South Indian, Kerala, North Indian",50% off | Use WELCOME50,4.4,32,300,Kochi
1,Usmans,"South Indian, Arabian",50% off | Use WELCOME50,3.6,18,150,Kochi
2,Pala Pepper,"Kerala, South Indian",50% off | Use WELCOME50,3.8,28,200,Kochi
3,Hotel Shree Aryas,"South Indian, North Indian, Chinese, Beverages",50% off | Use WELCOME50,4.2,24,200,Kochi
4,Hotel Sree Aryaas,"South Indian, North Indian, Chinese",50% off | Use WELCOME50,4.2,21,200,Kochi
...,...,...,...,...,...,...,...
79,Dindigul Biriyani,"Biryani, South Indian",50% off | Use WELCOME50,3.6,36,250,Kochi
80,pepper bite restaurant,"North Indian, Chinese, South Indian, Beverages",50% off | Use WELCOME50,3.9,42,280,Kochi
81,Nila Restaurant,"South Indian, North Indian, Chinese",50% off | Use WELCOME50,4.1,48,200,Kochi
82,Binnammas Food Gallery,"Kerala, South Indian, Chinese",50% off | Use WELCOME50,3.5,41,300,Kochi
83,Pakka Sabji,"Indian, Chinese, South Indian",50% off | Use WELCOME50,4.1,42,500,Kochi

In [236]:
df7.to_csv("df7.csv")

In [238]:
update_df7=df7.drop(index=[13,26,35,41,45,46,70,75])

In [239]:
update_df7

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,Alakapuri,"South Indian, Kerala, North Indian",50% off | Use WELCOME50,4.4,32,300,Kochi
1,Usmans,"South Indian, Arabian",50% off | Use WELCOME50,3.6,18,150,Kochi
2,Pala Pepper,"Kerala, South Indian",50% off | Use WELCOME50,3.8,28,200,Kochi
3,Hotel Shree Aryas,"South Indian, North Indian, Chinese, Beverages",50% off | Use WELCOME50,4.2,24,200,Kochi
4,Hotel Sree Aryaas,"South Indian, North Indian, Chinese",50% off | Use WELCOME50,4.2,21,200,Kochi
...,...,...,...,...,...,...,...
79,Dindigul Biriyani,"Biryani, South Indian",50% off | Use WELCOME50,3.6,36,250,Kochi
80,pepper bite restaurant,"North Indian, Chinese, South Indian, Beverages",50% off | Use WELCOME50,3.9,42,280,Kochi
81,Nila Restaurant,"South Indian, North Indian, Chinese",50% off | Use WELCOME50,4.1,48,200,Kochi
82,Binnammas Food Gallery,"Kerala, South Indian, Chinese",50% off | Use WELCOME50,3.5,41,300,Kochi
83,Pakka Sabji,"Indian, Chinese, South Indian",50% off | Use WELCOME50,4.1,42,500,Kochi

In [240]:
update_df7.to_csv("update_df7.csv")

In [255]:
v=pd.concat([update_df,update_df2,update_df3,update_df4,update_df5,update_df6,update_df7],axis=0)

In [256]:
v=v.reset_index(drop=True)

In [257]:
v

,Restaurant,Cuisine,Coupon,Rating,Delivery_time,Price per two,Location
0,Meghana Foods,"Biryani, Andhra, South Indian, North Indian, C...",50% off | Use WELCOME50,4.3,37,500,Bangalore
1,Ayodhya Upachar,"Chinese, Desserts, North Indian, South Indian,...",50% off | Use WELCOME50,4.4,36,200,Bangalore
2,Puliyogare Point,South Indian,50% off | Use WELCOME50,4.5,23,150,Bangalore
3,N R Donne Biriyani,"Biryani, South Indian",50% off | Use GUILTFREEJAN,4.2,31,250,Bangalore
4,Hotel Kadamba Veg,"South Indian, North Indian, Chinese, Sweets",50% off | Use WELCOME50,4.3,43,350,Bangalore
...,...,...,...,...,...,...,...
427,Dindigul Biriyani,"Biryani, South Indian",50% off | Use WELCOME50,3.6,36,250,Kochi
428,pepper bite restaurant,"North Indian, Chinese, South Indian, Beverages",50% off | Use WELCOME50,3.9,42,280,Kochi
429,Nila Restaurant,"South Indian, North Indian, Chinese",50% off | Use WELCOME50,4.1,48,200,Kochi
430,Binnammas Food Gallery,"Kerala, South Indian, Chinese",50% off | Use WELCOME50,3.5,41,300,Kochi
431,Pakka Sabji,"Indian, Chinese, South Indian",50% off | Use WELCOME50,4.1,42,500,Kochi

In [261]:
swiggy=v.iloc[:,[0,6,1,2,3,4,5]]

In [262]:
swiggy

,Restaurant,Location,Cuisine,Coupon,Rating,Delivery_time,Price per two
0,Meghana Foods,Bangalore,"Biryani, Andhra, South Indian, North Indian, C...",50% off | Use WELCOME50,4.3,37,500
1,Ayodhya Upachar,Bangalore,"Chinese, Desserts, North Indian, South Indian,...",50% off | Use WELCOME50,4.4,36,200
2,Puliyogare Point,Bangalore,South Indian,50% off | Use WELCOME50,4.5,23,150
3,N R Donne Biriyani,Bangalore,"Biryani, South Indian",50% off | Use GUILTFREEJAN,4.2,31,250
4,Hotel Kadamba Veg,Bangalore,"South Indian, North Indian, Chinese, Sweets",50% off | Use WELCOME50,4.3,43,350
...,...,...,...,...,...,...,...
427,Dindigul Biriyani,Kochi,"Biryani, South Indian",50% off | Use WELCOME50,3.6,36,250
428,pepper bite restaurant,Kochi,"North Indian, Chinese, South Indian, Beverages",50% off | Use WELCOME50,3.9,42,280
429,Nila Restaurant,Kochi,"South Indian, North Indian, Chinese",50% off | Use WELCOME50,4.1,48,200
430,Binnammas Food Gallery,Kochi,"Kerala, South Indian, Chinese",50% off | Use WELCOME50,3.5,41,300
431,Pakka Sabji,Kochi,"Indian, Chinese, South Indian",50% off | Use WELCOME50,4.1,42,500

In [263]:
swiggy["Rating"]=swiggy["Rating"].astype(float)

In [264]:
swiggy["Delivery_time"]=swiggy["Delivery_time"].astype(int)

In [265]:
swiggy["Price per two"]=swiggy["Price per two"].astype(int)

In [266]:
swiggy

,Restaurant,Location,Cuisine,Coupon,Rating,Delivery_time,Price per two
0,Meghana Foods,Bangalore,"Biryani, Andhra, South Indian, North Indian, C...",50% off | Use WELCOME50,4.3,37,500
1,Ayodhya Upachar,Bangalore,"Chinese, Desserts, North Indian, South Indian,...",50% off | Use WELCOME50,4.4,36,200
2,Puliyogare Point,Bangalore,South Indian,50% off | Use WELCOME50,4.5,23,150
3,N R Donne Biriyani,Bangalore,"Biryani, South Indian",50% off | Use GUILTFREEJAN,4.2,31,250
4,Hotel Kadamba Veg,Bangalore,"South Indian, North Indian, Chinese, Sweets",50% off | Use WELCOME50,4.3,43,350
...,...,...,...,...,...,...,...
427,Dindigul Biriyani,Kochi,"Biryani, South Indian",50% off | Use WELCOME50,3.6,36,250
428,pepper bite restaurant,Kochi,"North Indian, Chinese, South Indian, Beverages",50% off | Use WELCOME50,3.9,42,280
429,Nila Restaurant,Kochi,"South Indian, North Indian, Chinese",50% off | Use WELCOME50,4.1,48,200
430,Binnammas Food Gallery,Kochi,"Kerala, South Indian, Chinese",50% off | Use WELCOME50,3.5,41,300
431,Pakka Sabji,Kochi,"Indian, Chinese, South Indian",50% off | Use WELCOME50,4.1,42,500

In [267]:
swiggy.to_csv("swiggy_final.csv")